default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  host: localhost
  database: blogdb
  username: yam
  password: 1425
  port: 5432
  
test:
  <<: *default
  database: blogdb
production:
  <<: *default
  database: project_name_production
  username: project_name
  password: <%= ENV["PROJECT_NAME_DATABASE_PASSWORD"] %>